FROM node:18-alpine

WORKDIR /usr/src/app

# Install necessary build tools for Alpine
RUN apk add --no-cache python3 make g++ bash libc-dev



# Set environment variable to force bcrypt rebuild
# ENV BCRYPT_FORCE_REBUILD=1

COPY package*.json ./
RUN npm install
RUN npm install -g nodemon
RUN npm rebuild bcrypt --build-from-source



COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]