FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

# # Copy entrypoint script and ensure it's executable
# COPY entrypoint.sh ./entrypoint.sh
# RUN chmod +x ./entrypoint.sh

# Copy all the app files
COPY . .

EXPOSE 5000
# # Make sure entrypoint.sh is executed as a shell script
# ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]

# Set the default command (node server.js)
CMD ["npm", "run", "dev"]