FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

#COPY entrypoint.sh ./entrypoint.sh
#RUN chmod +x ./entrypoint.sh

COPY . .

EXPOSE 5000

#ENTRYPOINT ["./entrypoint.sh"]
CMD ["node", "server.js"]